name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # executa a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1️⃣ Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Gera o arquivo SVG
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3️⃣ Opcional: lista os arquivos gerados para debug
      - name: List files (debug)
        run: ls -R

      # 4️⃣ Envia o SVG para o branch output
      - name: Push pacman SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .  # o SVG é gerado na raiz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
